AirShip Enums + Example fillin
Minorusama/Impostor pull request #4
Opened 2021-04-19 10:21 UTC by JohnTranQUT

### Description
There are now 39 Tasks, was 40 in earlier versions, with #3 was unknown
Client must had changed.
Also added Example to Example Plugin for debugging purposes.

2021-04-19 10:59 UTC, Minorusama requested changes

2021-04-19 10:59 UTC, Minorusama commented on src/Impostor.Plugins.Example/Handlers/PlayerEventListener.cs
> +            if(e.Message == "completetasks")
Please fix spacing after `if`

2021-04-19 10:59 UTC, Minorusama commented on src/Impostor.Plugins.Example/Handlers/PlayerEventListener.cs
> +        public void t(IPlayerCompletedTaskEvent e)
Change to `OnPlayerCompleteTaskEvent`

2021-04-19 10:59 UTC, Minorusama commented on src/Impostor.Plugins.Example/Handlers/PlayerEventListener.cs
> +            _logger.LogInformation("Player {player} completed {task},{type},{category} visual {visual}", e.ClientPlayer.Character.PlayerInfo.PlayerName, e.Task.Task.Name, e.Task.Task.Type, e.Task.Tas
Please fix spacing after commas.
Change `e.ClientPlayer.Character` to `e.PlayerControl`

2021-04-19 10:59 UTC, Minorusama commented on src/Impostor.Plugins.Example/Handlers/PlayerEventListener.cs
> +                _ = e.PlayerControl.CompleteAllTasksAsync();
Use `await`

2021-04-20 05:58 UTC, JohnTranQUT reviewed
All done in 
Commitment: https://github.com/Minorusama/Impostor/pull/4/commits/d31c951b65d5d5c516bd0fef930663235e71cfb2

2021-04-20 07:37 UTC, merged